const ProfileActionTypes = {
  SET_MY_PROFILE: "SET_MY_PROFILE",

  CLEAR_MY_PROFILE: "CLEAR_MY_PROFILE",
  CLEAR_PROFILE: "CLEAR_PROFILE",

  FETCH_PROFILE_START: "FETCH_PROFILE_START",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",

  EDIT_BIO: "EDIT_BIO",

  EDIT_PHOTO_START: "EDIT_PHOTO_START",
  EDIT_PHOTO_END: "EDIT_PHOTO_END",

  EDIT_SOCIAL_START: "EDIT_SOCIAL_START",
  EDIT_SOCIAL_SUCCESS: "EDIT_SOCIAL_SUCCESS",
  EDIT_SOCIAL_FAILURE: "EDIT_SOCIAL_FAILURE",

  FOLLOW_START: "FOLLOW_START",
  FOLLOW_SUCCESS: "FOLLOW_SUCCESS",
  FOLLOW_FAILURE: "FOLLOW_FAILURE",
};

export default ProfileActionTypes;
